#!/bin/sh

## hyphop ##

url=`cat $0.link 2>/dev/null`

[ "$url" ] || url=`./bt_get_bynet`;

echo "[i] DL link: $url"

[ "$url" ] || {
echo "[e] link not defined"
exit 1
}

echo "[i] MAGNET CHK"

curl -s "http://bt.t-ru.org/ann?magnet" | hd


ariacnf="$ariacnf --enable-dht=false"
ariacnf="$ariacnf --enable-dht6=false"
ariacnf="$ariacnf --disable-ipv6=true"
ariacnf="$ariacnf --dht-file-path=/tmp/aria2.4.dht"
ariacnf="$ariacnf --dht-file-path6=/tmp/aria2.6.dht"

aria2c $ariacnf \
    --on-bt-download-complete="./hook.btc" \
    "$url"

#    --on-download-complete="./hook.dlc" \

echo "[i] OK"

echo "[i] what next ??? )))) "

exit 0




