#!/bin/sh

## hyphop ##

url=`cat $0.link 2>/dev/null`

[ "" ] && {
url_source="bt_get.linkup"

[ -s $url_source ] && {
    [ "$(cat $url_source)" ] && {
	echo "[i] get shared link from $url_source" >&2
	url=`./bt_get.show_get_link`
    }
}

}

echo "[i] DL link: $url"

[ "$url" ] || {
echo "[e] link not defined"
exit 1
}


echo "[i] MAGNET CHK"

curl -s "http://bt.t-ru.org/ann?magnet" | hd

aria2c \
    --dht-file-path=/tmp/aria2.4.dht \
    --dht-file-path6=/tmp/aria2.6.dht \
    --on-bt-download-complete="./hook.btc" \
    "$url"

#    --on-download-complete="./hook.dlc" \

echo "[i] OK"

echo "[i] what next ??? )))) "

exit 0




