#!/bin/bash

## hyphop ##

REP=share
ID=11019630
uploaded=.uploaded
user=free-acc0unt
token=7ce74c89a66
token="${token}8e026470a824b24dddad403c10b07"

#echo $token
#exit 0 

FILE="$1"
LABEL="$2"

[ -f "$FILE" ] || {
    echo "[e] not found $FILE" 1>&2
    exit 1
}


FFILE=$(readlink -f "$FILE")
FTYPE=$(file -b --mime-type "$FFILE")
FSIZE=$(stat -L -c%s "$FILE")

# test 
#FSIZE=10000000

FTYPE=application/gzip

[ "$FNAME" ] || {
    FNAME=$(basename "$FILE")
}


FNAME="$FNAME.gz"

[ "$LABEL" ] || {
    LABEL=$FNAME
}


echo "[i] UPLOAD $REP: $FNAME as $LABEL" 2>&1
echo "	$FILE($FTYPE) => $FFILE" 2>&1
echo "[i] upload size $FSIZE " 2>&1

#exit 0

#grep $FNAME .files && {
#    echo "[e] file already uploaded" 1>&2
#    exit 1
#}

U="$(curl -Gso /dev/null -w %{url_effective} --data-urlencode "$FNAME" "" | cut -c 3-)"
U="$(date +%s).gz"

url="https://uploads.github.com/repos/$user/$REP/releases/$ID/assets?name=$U"
echo "[i] url => $url"

#curl -v --write-out %{size_request} \
#    -H "Content-Type: application/octet-stream" \
#    --data-binary \@${FILE} \
#    $url

# -H "Authorization: token $token" \

#curl -v	\
#     --digest \


curl="curl"
#     -H "Transfer-Encoding: chunked" \

$curl -# \
     -o- \
     -v \
     --no-buffer \
     -u $user:$token \
     -H "Content-Length: $FSIZE" \
     -H "Content-Type: $FTYPE" \
    --upload-file "$FILE" \
    "$url" >> $uploaded

echo "" >> $uploaded

