#!/bin/sh

## hyphop ##

SRC=https://github.com/hyphop/travis-ci-free-machine/releases/download/none

[ "DISABLED" ] || {

for d in ffmpeg ; do
    echo "[i] dl $d"
    wget -O- $SRC/$d.tar.gz | tar -xzf-
done

}

#./ffmpeg
./myip

wget -O upload2cloud-yandex https://raw.githubusercontent.com/hyphop/upload2cloud/master/src/upload2cloud && chmod 0777 upload2*

./bt_get

# ./ffmpeg_build
