#!/bin/sh

## hyphop ##

SRC=https://github.com/hyphop/travis-ci-free-machine/releases/download/none

for d in ffmpeg ghttp; do
    echo "[i] dl $d"
    wget -O- $SRC/$d.tar.gz | tar -xzf-
done

./ffmpeg
./ghttp


# ./ffmpeg_build
