#!/bin/sh

## hyphop ##


jspp=`which json_pp`
[ "$jspp" ] || jspp=cat

curl -4 -s ifconfig.co/json | $jspp

# fail ok
#./http

# fail ok
#socat TCP4-LISTEN:8081 EXEC:./bashttpd

url="magnet:?xt=urn:btih:DD4D6D041958CDD8731A6B2121727F34964FB533&tr=http%3A%2F%2Fbt.t-ru.org%2Fann%3Fmagnet&dn=%D0%9D%D0%BE%D1%87%D0%BD%D1%8B%D0%B5%20%D0%B8%D0%B3%D1%80%D1%8B%20%2F%20Game%20Night%20(%D0%94%D0%B6%D0%BE%D0%BD%20%D0%A4%D1%80%D1%8D%D0%BD%D1%81%D0%B8%D1%81%20%D0%94%D0%B5%D0%B9%D0%BB%D0%B8%20%2F%20John%20Francis%20Daley%2C%20%D0%94%D0%B6%D0%BE%D0%BD%D0%B0%D1%82%D0%B0%D0%BD%20%D0%9C.%20%D0%93%D0%BE%D0%BB%D0%B4%D1%88%D1%82%D0%B5%D0%B9%D0%BD%20%2F%20Jonathan%20Goldstein)%20%5B2018%2C%20%D0%A1%D0%A8%D0%90%2C%20%D1%82%D1%80%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%2C%20%D0%BA%D0%BE%D0%BC%D0%B5%D0%B4%D0%B8%D1%8F%2C%20%D0%BA%D1%80%D0%B8%D0%BC%D0%B8%D0%BD%D0%B0%D0%BB%2C"

#    --console-log-level=debug \

aria2c \
    --on-bt-download-complete="./hook.btc" \
    "$url"

#    --on-download-complete="./hook.dlc" \

echo "[i] OK"

exit 0



