#!/bin/sh

## hyphop ##

#
# yandex free uploader account
#

src=https://webdav.yandex.com

DIR=FREE/

P="$1"

[ -d "$P" ] || {
    echo "[i] is not dir" >&2
    exit 1
}
F="$(basename "$P")"
S="$(stat -L -c%s "$P")"

time=`date +%s`

echo "[i] mkdir $F" >&2

# url encode
U="$(curl -Gso /dev/null -w %{url_effective} --data-urlencode "$F" "" | cut -c 3-)"

curl -# -o -  -v -L --basic --header "Authorization: Basic YWNjMHVudC5mcmVlOm9rZmNua3V4cm9penR5emQ=" \
    -X MKCOL $src/$DIR$U > /dev/null



