#!/bin/sh

## hyphop ##

#
# yandex free uploader account
#

src=https://webdav.yandex.com
#src=https://cloud.yandex.com

DIR=FREE/

F="$1"

[ -d "$F" ] || {
    echo "[i] is not dir" >&2
    exit 1
}

echo "[i] UP DIR => $F"

H=`cat $0-pw.conf`
H=${H%\ /}

#echo "$H----"
#exit 0

[ "$H" ] || {
    echo "[e] run $0-pw for config"
    exit 0
}

urlencode(){
# url encode
    echo "$(curl -Gso /dev/null -w %{url_effective} --data-urlencode "$1" "" | cut -c 3-)"
}


LIST=/tmp/up.curl

echo "" > $LIST

find "$F" -type d | while read d ; do
echo "[i] mkdir $d"
echo "url = \"$src/$DIR$(urlencode "$d")\"" >> $LIST
done

verbose="-v"

curl -#\
    $verbose -o - \
    -g \
    -L \
    -X MKCOL \
    -H "$H" \
    -K $LIST > /dev/null

echo "" > $LIST

[ "1" ] && {
find "$F" -type f | while read f ; do
S="$(stat -L -c%s "$f")"
echo "[i] up $f ($S bytes)"
echo "upload-file = \"$f\"
url = \"$src/$DIR$(urlencode "$f")\"
" >> $LIST
done

}

curl -#\
    $verbose -o - \
    -g \
    -L \
    -X PUT \
    -H "$H" \
    -K $LIST > /dev/null
#exit 0


