#!/bin/sh

## hyphop ##

#
# yandex free uploader account
#

src=https://webdav.yandex.com

DIR=FREE

F="$1"
S="$(stat -L -c%s "$F")"

time=`date +%s`

echo "[i] upload $S bytes"

U="$(curl -Gso /dev/null -w %{url_effective} --data-urlencode "$1" "" | cut -c 3-)"

curl -# -v -L --basic --header "Authorization: Basic YWNjMHVudC5mcmVlOm9rZmNua3V4cm9penR5emQ=" \
    -T "$F" $src/$DIR$U

