#!/bin/sh

## hyphop ##

#
# yandex free uploader account
#

src=https://webdav.yandex.com
#src=https://cloud.yandex.com

DIR=FREE/

P="$1"

[ -f "$P" ] || {
    echo "[i] is not file" >&2
    exit 1
}
F="$(basename "$P")"
S="$(stat -L -c%s "$P")"

time=`date +%s`

echo "[i] upload $F - $S bytes" >&2
H=`cat $0-pw.conf`
H=${H%\ /}

#echo "$H----"
#exit 0

[ "$H" ] || {
    echo "[e] run $0-pw for config"
    exit 0
}

# url encode
U="$(curl -Gso /dev/null -w %{url_effective} --data-urlencode "$F" "" | cut -c 3-)"

curl \
    -v -L \
    -H "$H" \
    -T "$P" $src/$DIR$U > /dev/null
