#!/bin/sh

## hyphop ##

echo "[i] $0 start"
VER=4.0
FFF=ffmpeg-$VER.tar.bz2
ff_src=https://ffmpeg.org/releases/$FFF

D=$PWD

[ -s $FFF ] || {
    echo "[w] exist already: $FFF"
}

    wget -c -O $FFF $ff_src




